# Generated by Django 2.2 on 2022-02-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_products_available'),
        ('cart', '0002_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item',
            new_name='items',
        ),
    ]
